$g_SubCommandAlias = @{
    'acm-pca'                      = 'pca';
    'application-autoscaling'      = 'aas';
    'alexaforbusiness'             = 'alxb';
    'apigateway'                   = 'ag';
    'apigatewaymanagementapi'      = 'agm';
    'apigatewayv2'                 = 'ag2';
    'appmesh'                      = 'amsh';
    'autoscaling'                  = 'as';
    'autoscaling-plans'            = 'asp';
    'clouddirectory'               = 'cdir';
    'cloudhsm'                     = 'hsm';
    'cloudhsmv2'                   = 'hsm2';
    'cloudsearch'                  = 'cs';
    'cloudwatch'                   = 'cw';
    'cognito-identity'             = 'cgi';
    'cognito-idp'                  = 'cgip';
    'cognito-sync'                 = 'cgis';
    'comprehend'                   = 'comp';
    'comprehendmedical'            = 'cmpm';
    'configservice'                = 'cfg';
    'connect'                      = 'conn';
    'datapipeline'                 = 'dp';
    'devicefarm'                   = 'df';
    'directconnect'                = 'dc';
    'docdb'                        = 'doc';
    'dynamodb'                     = 'ddb';
    'dynamodbstreams'              = 'ddb';
    'elasticbeanstalk'             = 'eb';
    'elastictranscoder'            = 'ets';
    'elbv2'                        = 'elb2';
    'globalaccelerator'            = 'gacl';
    'groundstation'                = 'gs';
    'importexport'                 = 'ie';
    'iot-jobs-data'                = 'iotj'
    'iotevents'                    = 'iote';
    'iotevents-data'               = 'ioted';
    'iotthingsgraph'               = 'iottg';
    'kinesis'                      = 'kin';
    'kinesis-video-media'          = 'kvm';
    'kinesisanalytics'             = 'kina';
    'kinesisanalyticsv2'           = 'kina2';
    'kinesisvideo'                 = 'kv';
    'lex-models'                   = 'lmb';
    'lex-runtime'                  = 'lex';
    'license-manager'              = 'licm';
    'machinelearning'              = 'ml';
    'marketplace-entitlement'      = 'mes';
    'marketplacecommerceanalytics' = 'mca';
    'managedblockchain'            = 'mbc';
    'mediastore'                   = 'ems';
    'mediastore-data'              = 'emsd';
    'mediapackage'                 = 'emp';
    'mediapackage-vod'             = 'empv';
    'meteringmarketplace'          = 'mm';
    'mgh'                          = 'mh';
    'opsworks'                     = 'ops';
    'opsworks-cm'                  = 'owcm';
    'pinpoint'                     = 'pin';
    'pinpoint-email'               = 'pine';
    'pinpoint-sms-voice'           = 'pine'
    'pricing'                      = 'pls';
    'rds-data'                     = 'rdsd';
    'resource-groups'              = 'rg';
    'resourcegroupstaggingapi'     = 'rgt';
    'route53'                      = 'r53';
    'route53domains'               = 'r53d';
    'route53resolver'              = 'r53r';
    's3control'                    = 's3c';
    'sagemaker'                    = 'sm';
    'sagemaker-runtime'            = 'smr';        
    'secretsmanager'               = 'sec';
    'securityhub'                  = 'shub';
    'serverlessrepo'               = 'sar';
    'service-quotas'               = 'sq';
    'servicecatalog'               = 'sc';
    'servicediscovery'             = 'sd';
    'stepfunctions'                = 'sfn';
    'storagegateway'               = 'sg';
    'waf-regional'                 = 'wafr';
    'xray'                         = 'xr'
}

$g_AWSServices = @{
    'acm'                          = [PSCustomObject]@{ Prefix = 'ACM'; Name = 'AWS Certificate Manager'; Url = 'https://aws.amazon.com/certificate-manager/'; Note = '' };
    'acm-pca'                      = [PSCustomObject]@{ Prefix = 'PCA'; Name = 'AWS Certificate Manager Private Certificate Authority'; Url = 'https://aws.amazon.com/certificate-manager/'; Note = '' };
    'alexaforbusiness'             = [PSCustomObject]@{ Prefix = 'ALXB'; Name = 'Alexa for Business'; Url = 'https://aws.amazon.com/alexaforbusiness/'; Note = '' };
    'amplify'                      = [PSCustomObject]@{ Prefix = 'AMP'; Name = 'AWS Amplify'; Url = 'https://aws.amazon.com/amplify/'; Note = '' };
    'apigateway'                   = [PSCustomObject]@{ Prefix = 'AG'; Name = 'Amazon API Gateway'; Url = 'https://aws.amazon.com/api-gateway/'; Note = '' };
    'apigatewaymanagementapi'      = [PSCustomObject]@{ Prefix = 'AGM'; Name = 'Amazon API Gateway Management'; Url = 'https://aws.amazon.com/api-gateway/'; Note = '' };
    'apigatewayv2'                 = [PSCustomObject]@{ Prefix = 'AG2'; Name = 'Amazon API Gateway'; Url = 'https://aws.amazon.com/api-gateway/'; Note = '' };
    'application-autoscaling'      = [PSCustomObject]@{ Prefix = 'AAS'; Name = 'AWS Auto Scaling'; Url = 'https://aws.amazon.com/autoscaling/'; Note = '' };
    'application-insigths'         = [PSCustomObject]@{ Prefix = 'CWAI'; Name = 'Amazon CloudWatch Application Insights for .NET and SQL Server'; Url = 'http://docs.amazonaws.cn/en_us/AmazonCloudWatch/latest/monitoring/cloudwatch-application-insights.html'; Note = '' };
    'appmesh'                      = [PSCustomObject]@{ Prefix = 'AMSH'; Name = 'AWS App Mesh'; Url = 'https://aws.amazon.com/app-mesh/'; Note = '' };
    'appstream'                    = [PSCustomObject]@{ Prefix = 'APS'; Name = 'Amazon AppStream 2.0'; Url = 'https://aws.amazon.com/appstream2/'; Note = '' };
    'appsync'                      = [PSCustomObject]@{ Prefix = 'ASYN'; Name = 'AWS AppSync'; Url = 'https://aws.amazon.com/appsync/'; Note = '' };
    'athena'                       = [PSCustomObject]@{ Prefix = 'ATH'; Name = 'Amazon Athena'; Url = 'https://aws.amazon.com/athena/'; Note = '' };
    'autoscaling'                  = [PSCustomObject]@{ Prefix = 'AS'; Name = 'AWS Auto Scaling'; Url = 'https://aws.amazon.com/autoscaling/'; Note = '' };
    'autoscaling-plans'            = [PSCustomObject]@{ Prefix = 'ASP'; Name = 'AWS Auto Scaling'; Url = 'https://aws.amazon.com/autoscaling/'; Note = '' };
    'backup'                       = [PSCustomObject]@{ Prefix = 'BAK'; Name = 'AWS Backup'; Url = 'https://aws.amazon.com/backup/'; Note = '' };
    'batch'                        = [PSCustomObject]@{ Prefix = 'BAT'; Name = 'AWS Batch'; Url = 'https://aws.amazon.com/batch/'; Note = '' };
    'budgets'                      = [PSCustomObject]@{ Prefix = 'BGT'; Name = 'AWS Budgets'; Url = 'https://aws.amazon.com/aws-cost-management/aws-budgets/'; Note = '' };
    'ce'                           = [PSCustomObject]@{ Prefix = 'CE'; Name = 'Cost Explorer'; Url = 'https://aws.amazon.com/aws-cost-management/aws-cost-explorer/'; Note = '' };
    'chime'                        = [PSCustomObject]@{ Prefix = 'CHM'; Name = 'Amazon Chime'; Url = 'https://aws.amazon.com/chime/'; Note = '' };
    'cloud9'                       = [PSCustomObject]@{ Prefix = 'C9'; Name = 'AWS Cloud9'; Url = 'https://aws.amazon.com/cloud9/'; Note = '' };
    'clouddirectory'               = [PSCustomObject]@{ Prefix = 'CDIR'; Name = 'Amazon Cloud Directory'; Url = 'https://aws.amazon.com/cloud-directory/'; Note = '' };
    'cloudformation'               = [PSCustomObject]@{ Prefix = 'CFN'; Name = 'AWS Cloud​Formation'; Url = 'https://aws.amazon.com/cloudformation/'; Note = '' };
    'cloudfront'                   = [PSCustomObject]@{ Prefix = 'CF'; Name = 'Amazon CloudFront'; Url = 'https://aws.amazon.com/cloudfront/'; Note = '' };
    'cloudhsm'                     = [PSCustomObject]@{ Prefix = 'HSM'; Name = 'AWS CloudHSM'; Url = 'https://aws.amazon.com/cloudhsm/'; Note = '' };
    'cloudhsmv2'                   = [PSCustomObject]@{ Prefix = 'HSM2'; Name = 'AWS CloudHSM'; Url = 'https://aws.amazon.com/cloudhsm/'; Note = '' };
    'cloudsearch'                  = [PSCustomObject]@{ Prefix = 'CS'; Name = 'Amazon CloudSearch'; Url = 'https://aws.amazon.com/cloudsearch/'; Note = '' };
    'cloudsearchdomain'            = [PSCustomObject]@{ Prefix = 'CSD'; Name = 'Amazon CloudSearch'; Url = 'https://aws.amazon.com/cloudsearch/'; Note = '' };
    'cloudtrail'                   = [PSCustomObject]@{ Prefix = 'CT'; Name = 'AWS CloudTrail'; Url = 'https://aws.amazon.com/cloudtrail/'; Note = '' };
    'cloudwatch'                   = [PSCustomObject]@{ Prefix = 'CW'; Name = 'Amazon CloudWatch'; Url = 'https://aws.amazon.com/cloudwatch/'; Note = '' };
    'codebuild'                    = [PSCustomObject]@{ Prefix = 'CB'; Name = 'AWS CodeBuild'; Url = 'https://aws.amazon.com/codebuild/'; Note = '' };
    'codecommit'                   = [PSCustomObject]@{ Prefix = 'CC'; Name = 'AWS CodeCommit'; Url = 'https://aws.amazon.com/codecommit/'; Note = '' };
    'codepipeline'                 = [PSCustomObject]@{ Prefix = 'CP'; Name = 'AWS CodePipeline'; Url = 'https://aws.amazon.com/codepipeline/'; Note = '' };
    'codestar'                     = [PSCustomObject]@{ Prefix = 'CST'; Name = 'AWS CodeStar'; Url = 'https://aws.amazon.com/codestar/'; Note = '' };
    'cognito-identity'             = [PSCustomObject]@{ Prefix = 'CGI'; Name = 'Amazon Cognito uniquely identifies'; Url = 'https://aws.amazon.com/cognito/'; Note = '' };
    'cognito-idp'                  = [PSCustomObject]@{ Prefix = 'CGIP'; Name = 'Amazon Cognito Identity Provider'; Url = 'https://aws.amazon.com/cognito/'; Note = '' };
    'cognito-sync'                 = [PSCustomObject]@{ Prefix = 'CGIS'; Name = 'Amazon Cognito Sync'; Url = 'https://aws.amazon.com/cognito/'; Note = '' };
    'comprehend'                   = [PSCustomObject]@{ Prefix = 'COMP'; Name = 'Amazon Comprehend'; Url = 'https://aws.amazon.com/comprehend/'; Note = '' };
    'comprehendmedical'            = [PSCustomObject]@{ Prefix = 'CMPM'; Name = 'Amazon Comprehend'; Url = 'https://aws.amazon.com/comprehend/'; Note = '' };
    'configservice'                = [PSCustomObject]@{ Prefix = 'CFG'; Name = 'AWS Config'; Url = 'https://aws.amazon.com/config/'; Note = '' };
    'configure'                    = [PSCustomObject]@{ Prefix = ''; Name = '-'; Url = ''; Note = 'Configure AWS CLI options.' };
    'connect'                      = [PSCustomObject]@{ Prefix = 'CONN'; Name = 'Amazon Connect'; Url = 'https://aws.amazon.com/connect/'; Note = '' };
    'cur'                          = [PSCustomObject]@{ Prefix = 'CUR'; Name = 'AWS Cost and Usage Report'; Url = 'https://aws.amazon.com/aws-cost-management/aws-cost-and-usage-reporting/'; Note = '' };
    'datapipeline'                 = [PSCustomObject]@{ Prefix = 'DP'; Name = 'AWS Data Pipeline'; Url = 'https://aws.amazon.com/datapipeline/'; Note = '' };
    'datasync'                     = [PSCustomObject]@{ Prefix = 'DSYN'; Name = 'AWS DataSync'; Url = 'https://aws.amazon.com/datasync/'; Note = '' };
    'dax'                          = [PSCustomObject]@{ Prefix = 'DAX'; Name = 'Amazon DynamoDB Accelerator'; Url = 'https://aws.amazon.com/dynamodb/'; Note = '' };
    'deploy'                       = [PSCustomObject]@{ Prefix = 'CD'; Name = 'AWS CodeDeploy'; Url = 'https://aws.amazon.com/codedeploy/'; Note = '' };
    'devicefarm'                   = [PSCustomObject]@{ Prefix = 'DF'; Name = 'AWS Device Farm'; Url = 'https://aws.amazon.com/device-farm/'; Note = '' };
    'directconnect'                = [PSCustomObject]@{ Prefix = 'DC'; Name = 'AWS Direct Connect'; Url = 'https://aws.amazon.com/directconnect/'; Note = '' };
    'discovery'                    = [PSCustomObject]@{ Prefix = 'ADS'; Name = 'AWS Application Discovery Service'; Url = 'https://aws.amazon.com/application-discovery/'; Note = '' };
    'dlm'                          = [PSCustomObject]@{ Prefix = 'DLM'; Name = 'Amazon Data Lifecycle Manager'; Url = 'https://aws.amazon.com/ebs/'; Note = '' };
    'dms'                          = [PSCustomObject]@{ Prefix = 'DMS'; Name = 'AWS Database Migration Service'; Url = 'https://aws.amazon.com/dms/'; Note = '' };
    'docdb'                        = [PSCustomObject]@{ Prefix = 'DOC'; Name = 'Amazon DocumentDB'; Url = 'https://aws.amazon.com/documentdb/'; Note = '' };
    'ds'                           = [PSCustomObject]@{ Prefix = 'DS'; Name = 'AWS Directory Service'; Url = 'https://aws.amazon.com/directoryservice/'; Note = '' };
    'dynamodb'                     = [PSCustomObject]@{ Prefix = 'DDB'; Name = 'Amazon DynamoDB'; Url = 'https://aws.amazon.com/dynamodb/'; Note = '' };
    'dynamodbstreams'              = [PSCustomObject]@{ Prefix = 'DDB'; Name = 'Amazon DynamoDB Streams'; Url = 'https://aws.amazon.com/dynamodb/'; Note = '' };
    'ec2'                          = [PSCustomObject]@{ Prefix = 'EC2'; Name = 'Amazon EC2'; Url = 'https://aws.amazon.com/ec2/'; Note = '' };
    'ec2-instance-connect'         = [PSCustomObject]@{ Prefix = ''; Name = 'AWS EC2 Connect Service'; Url = 'https://aws.amazon.com/ec2/'; Note = '' };
    'ecr'                          = [PSCustomObject]@{ Prefix = 'ECR'; Name = 'Amazon Elastic Container Registry'; Url = 'https://aws.amazon.com/ecr/'; Note = '' };
    'ecs'                          = [PSCustomObject]@{ Prefix = 'ECS'; Name = 'Amazon Elastic Container Service'; Url = 'https://aws.amazon.com/ecs/'; Note = '' };
    'efs'                          = [PSCustomObject]@{ Prefix = 'EFS'; Name = 'Amazon Elastic File System'; Url = 'https://aws.amazon.com/efs/'; Note = '' };
    'eks'                          = [PSCustomObject]@{ Prefix = 'EKS'; Name = 'Amazon Elastic Container Service for Kubernetes'; Url = 'https://aws.amazon.com/eks/'; Note = '' };
    'elasticache'                  = [PSCustomObject]@{ Prefix = 'EC'; Name = 'Amazon ElastiCache'; Url = 'https://aws.amazon.com/elasticache/'; Note = '' };
    'elasticbeanstalk'             = [PSCustomObject]@{ Prefix = 'EB'; Name = 'AWS Elastic Beanstalk'; Url = 'https://aws.amazon.com/elasticbeanstalk/'; Note = '' };
    'elastictranscoder'            = [PSCustomObject]@{ Prefix = 'ETS'; Name = 'Amazon Elastic Transcoder'; Url = 'https://aws.amazon.com/elastictranscoder/'; Note = '' };
    'elb'                          = [PSCustomObject]@{ Prefix = 'ELB'; Name = 'Elastic Load Balancing'; Url = 'https://aws.amazon.com/elasticloadbalancing/'; Note = '' };
    'elbv2'                        = [PSCustomObject]@{ Prefix = 'ELB2'; Name = 'Elastic Load Balancing'; Url = 'https://aws.amazon.com/elasticloadbalancing/'; Note = '' };
    'emr'                          = [PSCustomObject]@{ Prefix = 'EMR'; Name = 'Amazon EMR'; Url = 'https://aws.amazon.com/emr/'; Note = '' };
    'es'                           = [PSCustomObject]@{ Prefix = 'ES'; Name = 'Amazon Elasticsearch Service'; Url = 'https://aws.amazon.com/elasticsearch-service/'; Note = '' };
    'events'                       = [PSCustomObject]@{ Prefix = 'CWE'; Name = 'Amazon CloudWatch Events'; Url = 'https://aws.amazon.com/cloudwatch/'; Note = '' };
    'firehose'                     = [PSCustomObject]@{ Prefix = 'KINF'; Name = 'Amazon Kinesis Data Firehose'; Url = 'https://aws.amazon.com/data-firehose/'; Note = '' };
    'fms'                          = [PSCustomObject]@{ Prefix = 'FMS'; Name = 'AWS Firewall Manager'; Url = 'https://aws.amazon.com/waf/'; Note = '' };
    'fsx'                          = [PSCustomObject]@{ Prefix = 'FSX'; Name = 'Amazon FSx'; Url = 'https://aws.amazon.com/fsx/'; Note = '' };
    'gamelift'                     = [PSCustomObject]@{ Prefix = 'GML'; Name = 'Amazon GameLift'; Url = 'https://aws.amazon.com/gamelift/'; Note = '' };
    'glacier'                      = [PSCustomObject]@{ Prefix = 'GLC'; Name = 'Amazon S3 Glacier'; Url = 'https://aws.amazon.com/glacier/'; Note = '' };
    'globalaccelerator'            = [PSCustomObject]@{ Prefix = 'GACL'; Name = 'AWS Global Accelerator'; Url = 'https://aws.amazon.com/global-accelerator/'; Note = '' };
    'glue'                         = [PSCustomObject]@{ Prefix = 'GLUE'; Name = 'AWS Glue'; Url = 'https://aws.amazon.com/glue/'; Note = '' };
    'greengrass'                   = [PSCustomObject]@{ Prefix = 'GG'; Name = 'AWS IoT Greengrass'; Url = 'https://aws.amazon.com/greengrass/'; Note = '' };
    'groundstation'                = [PSCustomObject]@{ Prefix = 'GS'; Name = 'AWS Ground Station'; Url = 'https://aws.amazon.com/ground-station/'; Note = '' };
    'guardduty'                    = [PSCustomObject]@{ Prefix = 'GD'; Name = 'Amazon Guard​Duty'; Url = 'https://aws.amazon.com/guardduty/'; Note = '' };
    'health'                       = [PSCustomObject]@{ Prefix = 'HLTH'; Name = 'AWS Health'; Url = 'https://phd.aws.amazon.com/'; Note = '' };
    'history'                      = [PSCustomObject]@{ Prefix = ''; Name = '-'; Url = ''; Note = 'Commands to interact with the history of AWS CLI commands ran over time.' };
    'iam'                          = [PSCustomObject]@{ Prefix = 'IAM'; Name = 'AWS Identity and Access Management'; Url = 'https://aws.amazon.com/iam/'; Note = '' };
    'importexport'                 = [PSCustomObject]@{ Prefix = 'IE'; Name = 'AWS Import/Export'; Url = 'https://aws.amazon.com/snowball/'; Note = '' };
    'inspector'                    = [PSCustomObject]@{ Prefix = 'INS'; Name = 'Amazon Inspector'; Url = 'https://aws.amazon.com/inspector/'; Note = '' };
    'iot'                          = [PSCustomObject]@{ Prefix = 'IOT'; Name = 'AWS IoT'; Url = 'https://aws.amazon.com/iot/'; Note = '' };
    'iot-data'                     = [PSCustomObject]@{ Prefix = ''; Name = 'AWS IoT-Data'; Url = 'https://aws.amazon.com/iot/'; Note = '' };
    'iot-jobs-data'                = [PSCustomObject]@{ Prefix = 'IOTJ'; Name = 'AWS IoT Jobs'; Url = 'https://aws.amazon.com/iot/'; Note = '' };
    'iot1click-devices'            = [PSCustomObject]@{ Prefix = ''; Name = 'AWS IoT 1-Click Devices'; Url = 'https://aws.amazon.com/iot/'; Note = '' };
    'iot1click-projects'           = [PSCustomObject]@{ Prefix = ''; Name = 'AWS IoT 1-Click Project'; Url = 'https://aws.amazon.com/iot/'; Note = '' };
    'iotanalytics'                 = [PSCustomObject]@{ Prefix = ''; Name = 'AWS IoT Analytics'; Url = 'https://aws.amazon.com/iot/'; Note = '' };
    'iotevents'                    = [PSCustomObject]@{ Prefix = 'IOTE'; Name = 'AWS IoT Events'; Url = 'https://aws.amazon.com/iot-events/'; Note = '' };
    'iotevents-data'               = [PSCustomObject]@{ Prefix = 'IOTED'; Name = 'AWS IoT Events'; Url = 'https://aws.amazon.com/iot-events/'; Note = '' };
    'iotthingsgraph'               = [PSCustomObject]@{ Prefix = 'IOTTG'; Name = 'AWS IoT Things Graph'; Url = 'https://aws.amazon.com/iot-things-graph/'; Note = '' };
    'kafka'                        = [PSCustomObject]@{ Prefix = 'MSK'; Name = 'Amazon Managed Streaming for Kafka'; Url = 'https://aws.amazon.com/msk/'; Note = '' };
    'kinesis'                      = [PSCustomObject]@{ Prefix = 'KIN'; Name = 'Amazon Kinesis'; Url = 'https://aws.amazon.com/kinesis/'; Note = '' };
    'kinesis-video-archived-media' = [PSCustomObject]@{ Prefix = ''; Name = 'Amazon Kinesis'; Url = 'https://aws.amazon.com/kinesis/'; Note = '' };
    'kinesis-video-media'          = [PSCustomObject]@{ Prefix = 'KVM'; Name = 'Amazon Kinesis Video Streams Media'; Url = 'https://aws.amazon.com/kinesis/'; Note = '' };
    'kinesisanalytics'             = [PSCustomObject]@{ Prefix = 'KINA'; Name = 'Amazon Kinesis'; Url = 'https://aws.amazon.com/kinesis/'; Note = '' };
    'kinesisanalyticsv2'           = [PSCustomObject]@{ Prefix = 'KINA2'; Name = 'Amazon Kinesis'; Url = 'https://aws.amazon.com/kinesis/'; Note = '' };
    'kinesisvideo'                 = [PSCustomObject]@{ Prefix = 'KV'; Name = 'Amazon Kinesis'; Url = 'https://aws.amazon.com/kinesis/'; Note = '' };
    'kms'                          = [PSCustomObject]@{ Prefix = 'KMS'; Name = 'AWS Key Management Service'; Url = 'https://aws.amazon.com/kms/'; Note = '' };
    'lambda'                       = [PSCustomObject]@{ Prefix = 'LM'; Name = 'AWS Lambda'; Url = 'https://aws.amazon.com/lambda/'; Note = '' };
    'lex-models'                   = [PSCustomObject]@{ Prefix = 'LMB'; Name = 'Amazon Lex'; Url = 'https://aws.amazon.com/lex/'; Note = '' };
    'lex-runtime'                  = [PSCustomObject]@{ Prefix = 'LEX'; Name = 'Amazon Lex'; Url = 'https://aws.amazon.com/lex/'; Note = '' };
    'license-manager'              = [PSCustomObject]@{ Prefix = 'LICM'; Name = 'AWS License Manager'; Url = 'https://aws.amazon.com/license-manager/'; Note = '' };
    'lightsail'                    = [PSCustomObject]@{ Prefix = 'LS'; Name = 'Amazon Lightsail'; Url = 'https://aws.amazon.com/lightsail/'; Note = '' };
    'logs'                         = [PSCustomObject]@{ Prefix = 'CWL'; Name = 'Amazon CloudWatch Logs'; Url = 'https://aws.amazon.com/cloudwatch/'; Note = '' };
    'machinelearning'              = [PSCustomObject]@{ Prefix = 'ML'; Name = 'Amazon Machine Learning'; Url = 'https://aws.amazon.com/machinelearning/'; Note = '' };
    'macie'                        = [PSCustomObject]@{ Prefix = 'MAC'; Name = 'Amazon Macie'; Url = 'https://aws.amazon.com/macie/'; Note = '' };
    'managedblockchain'            = [PSCustomObject]@{ Prefix = 'MBC'; Name = 'Amazon Managed Blockchain'; Url = 'https://aws.amazon.com/jp/managed-blockchain/'; Note = '' };
    'marketplace-entitlement'      = [PSCustomObject]@{ Prefix = 'MES'; Name = 'AWS Marketplace Entitlement Service'; Url = 'https://aws.amazon.com/marketplace/'; Note = '' };
    'marketplacecommerceanalytics' = [PSCustomObject]@{ Prefix = 'MCA'; Name = 'AWS Marketplace Commerce Analytics'; Url = 'https://aws.amazon.com/marketplace/'; Note = '' };
    'mediaconnect'                 = [PSCustomObject]@{ Prefix = 'EMCN'; Name = 'AWS Elemental MediaConnect'; Url = 'https://aws.amazon.com/mediaconnect/'; Note = '' };
    'mediaconvert'                 = [PSCustomObject]@{ Prefix = 'EMC'; Name = 'AWS Elemental MediaConvert'; Url = 'https://aws.amazon.com/mediaconvert/'; Note = '' };
    'medialive'                    = [PSCustomObject]@{ Prefix = 'EML'; Name = 'AWS Elemental MediaLive'; Url = 'https://aws.amazon.com/medialive/'; Note = '' };
    'mediapackage'                 = [PSCustomObject]@{ Prefix = 'EMP'; Name = 'AWS Elemental MediaPackage'; Url = 'https://aws.amazon.com/mediapackage/'; Note = '' };
    'mediapackage-vod'             = [PSCustomObject]@{ Prefix = 'EMPV'; Name = 'AWS Elemental MediaPackage VOD'; Url = 'https://aws.amazon.com/mediapackage/'; Note = '' };
    'mediastore'                   = [PSCustomObject]@{ Prefix = 'EMS'; Name = 'AWS Elemental MediaStore'; Url = 'https://aws.amazon.com/mediastore/'; Note = '' };
    'mediastore-data'              = [PSCustomObject]@{ Prefix = 'EMSD'; Name = 'AWS Elemental MediaStore Data Plane'; Url = 'https://aws.amazon.com/mediastore/'; Note = '' };
    'mediatailor'                  = [PSCustomObject]@{ Prefix = 'EMT'; Name = 'AWS Elemental MediaTailor'; Url = 'https://aws.amazon.com/mediatailor/'; Note = '' };
    'meteringmarketplace'          = [PSCustomObject]@{ Prefix = 'MM'; Name = 'AWS Marketplace Metering Service'; Url = 'https://aws.amazon.com/marketplace/'; Note = '' };
    'mgh'                          = [PSCustomObject]@{ Prefix = 'MH'; Name = 'AWS Migration Hub'; Url = 'https://aws.amazon.com/migration-hub/'; Note = '' };
    'mobile'                       = [PSCustomObject]@{ Prefix = 'MOBL'; Name = 'AWS Mobile'; Url = 'https://aws.amazon.com/amplify/'; Note = '' };
    'mq'                           = [PSCustomObject]@{ Prefix = 'MQ'; Name = 'Amazon MQ'; Url = 'https://aws.amazon.com/amazon-mq/'; Note = '' };
    'mturk'                        = [PSCustomObject]@{ Prefix = 'MTR'; Name = 'Amazon Mechanical Turk'; Url = 'https://www.mturk.com/'; Note = '' };
    'neptune'                      = [PSCustomObject]@{ Prefix = 'NPT'; Name = 'Amazon Neptune'; Url = 'https://aws.amazon.com/neptune/'; Note = '' };
    'opsworks'                     = [PSCustomObject]@{ Prefix = 'OPS'; Name = 'AWS OpsWorks'; Url = 'https://aws.amazon.com/opsworks/'; Note = '' };
    'opsworks-cm'                  = [PSCustomObject]@{ Prefix = 'OWCM'; Name = 'AWS OpsWorks for configuration management'; Url = 'https://aws.amazon.com/opsworks/'; Note = '' };
    'organizations'                = [PSCustomObject]@{ Prefix = 'ORG'; Name = 'AWS Organizations'; Url = 'https://aws.amazon.com/organizations/'; Note = '' };
    'personalize'                  = [PSCustomObject]@{ Prefix = ''; Name = 'Amazon Personalize'; Url = 'https://aws.amazon.com/personalize/'; Note = '' };
    'personalize-events'           = [PSCustomObject]@{ Prefix = ''; Name = 'Amazon Personalize'; Url = 'https://aws.amazon.com/personalize/'; Note = '' };
    'personalize-runtime'          = [PSCustomObject]@{ Prefix = ''; Name = 'Amazon Personalize'; Url = 'https://aws.amazon.com/personalize/'; Note = '' };
    'pi'                           = [PSCustomObject]@{ Prefix = 'PI'; Name = 'AWS Performance Insights'; Url = 'https://aws.amazon.com/rds/performance-insights/'; Note = '' };
    'pinpoint'                     = [PSCustomObject]@{ Prefix = 'PIN'; Name = 'Amazon Pinpoint'; Url = 'https://aws.amazon.com/pinpoint/'; Note = '' };
    'pinpoint-email'               = [PSCustomObject]@{ Prefix = 'PINE'; Name = 'Amazon Pinpoint Email'; Url = 'https://aws.amazon.com/pinpoint/'; Note = '' };
    'pinpoint-sms-voice'           = [PSCustomObject]@{ Prefix = 'PINE'; Name = 'Amazon Pinpoint SMS and Voice Messaging'; Url = 'https://aws.amazon.com/pinpoint/'; Note = '' };
    'polly'                        = [PSCustomObject]@{ Prefix = 'POL'; Name = 'Amazon Polly'; Url = 'https://aws.amazon.com/pinpoint/polly/'; Note = '' };
    'pricing'                      = [PSCustomObject]@{ Prefix = 'PLS'; Name = 'AWS Price List Service'; Url = 'https://aws.amazon.com/pricing/'; Note = '' };
    'quicksight'                   = [PSCustomObject]@{ Prefix = 'QS'; Name = 'Amazon QuickSight'; Url = 'https://aws.amazon.com/quicksight/'; Note = '' };
    'ram'                          = [PSCustomObject]@{ Prefix = 'RAM'; Name = 'AWS Resource Access Manager'; Url = 'https://aws.amazon.com/ram/'; Note = '' };
    'rds'                          = [PSCustomObject]@{ Prefix = 'RDS'; Name = 'Amazon Relational Database Service'; Url = 'https://aws.amazon.com/rds/'; Note = '' };
    'rds-data'                     = [PSCustomObject]@{ Prefix = 'RDSD'; Name = 'Amazon Relational Database Service'; Url = 'https://aws.amazon.com/rds/'; Note = '' };
    'redshift'                     = [PSCustomObject]@{ Prefix = 'RS'; Name = 'Amazon Redshift'; Url = 'https://aws.amazon.com/redshift/'; Note = '' };
    'rekognition'                  = [PSCustomObject]@{ Prefix = 'REK'; Name = 'Amazon Rekognition'; Url = 'https://aws.amazon.com/rekognition/'; Note = '' };
    'resource-groups'              = [PSCustomObject]@{ Prefix = 'RG'; Name = 'AWS Resource Groups'; Url = 'https://aws.amazon.com/'; Note = '' };
    'resourcegroupstaggingapi'     = [PSCustomObject]@{ Prefix = 'RGT'; Name = 'AWS Resource Groups Tagging'; Url = 'https://aws.amazon.com/'; Note = '' };
    'robomaker'                    = [PSCustomObject]@{ Prefix = 'ROBO'; Name = 'AWS RoboMaker'; Url = 'https://aws.amazon.com/robomaker/'; Note = '' };
    'route53'                      = [PSCustomObject]@{ Prefix = 'R53'; Name = 'Amazon Route 53'; Url = 'https://aws.amazon.com/route53/'; Note = '' };
    'route53domains'               = [PSCustomObject]@{ Prefix = 'R53D'; Name = 'Amazon Route 53 Domains'; Url = 'https://aws.amazon.com/route53/'; Note = '' };
    'route53resolver'              = [PSCustomObject]@{ Prefix = 'R53R'; Name = 'Amazon Route 53 Resolver'; Url = 'https://aws.amazon.com/route53/'; Note = '' };
    's3'                           = [PSCustomObject]@{ Prefix = 'S3'; Name = 'Amazon S3'; Url = 'https://aws.amazon.com/s3/'; Note = '* Currntly, failed to create the list...' };
    's3api'                        = [PSCustomObject]@{ Prefix = 'S3'; Name = 'Amazon S3'; Url = 'https://aws.amazon.com/s3/'; Note = '* Currntly, failed to create the list...' };
    's3control'                    = [PSCustomObject]@{ Prefix = 'S3C'; Name = 'Amazon S3'; Url = 'https://aws.amazon.com/s3/'; Note = '' };
    'sagemaker'                    = [PSCustomObject]@{ Prefix = 'SM'; Name = 'Amazon SageMaker'; Url = 'https://aws.amazon.com/sagemaker/'; Note = '' };
    'sagemaker-runtime'            = [PSCustomObject]@{ Prefix = 'SMR'; Name = 'Amazon SageMaker'; Url = 'https://aws.amazon.com/sagemaker/'; Note = '' };
    'sdb'                          = [PSCustomObject]@{ Prefix = ''; Name = 'Amazon SimpleDB'; Url = 'https://aws.amazon.com/simpledb/'; Note = '' };
    'secretsmanager'               = [PSCustomObject]@{ Prefix = 'SEC'; Name = 'AWS Secrets Manager'; Url = 'https://aws.amazon.com/secrets-manager/'; Note = '' };
    'securityhub'                  = [PSCustomObject]@{ Prefix = 'SHUB'; Name = 'AWS Security Hub'; Url = 'https://aws.amazon.com/securityhub/'; Note = '' };
    'serverlessrepo'               = [PSCustomObject]@{ Prefix = 'SAR'; Name = 'AWS Serverless Application Repository'; Url = 'https://aws.amazon.com/serverless/serverlessrepo/'; Note = '' };
    'service-quotas'               = [PSCustomObject]@{ Prefix = 'SQ'; Name = 'AWS Service Quotas'; Url = 'https://console.aws.amazon.com/servicequotas/'; Note = '' };
    'servicecatalog'               = [PSCustomObject]@{ Prefix = 'SC'; Name = 'AWS Service Catalog'; Url = 'https://aws.amazon.com/servicecatalog/'; Note = '' };
    'servicediscovery'             = [PSCustomObject]@{ Prefix = 'SD'; Name = 'Amazon Route 53 Auto Naming'; Url = 'https://aws.amazon.com/route53/'; Note = '' };
    'ses'                          = [PSCustomObject]@{ Prefix = 'SES'; Name = 'Amazon Simple Email Service'; Url = 'https://aws.amazon.com/ses/'; Note = '' };
    'shield'                       = [PSCustomObject]@{ Prefix = 'SHLD'; Name = 'AWS Shield'; Url = 'https://aws.amazon.com/shield/'; Note = '' };
    'signer'                       = [PSCustomObject]@{ Prefix = ''; Name = 'AWS Signer'; Url = 'https://docs.aws.amazon.com/signer/latest/api/Welcome.html'; Note = '' };
    'sms'                          = [PSCustomObject]@{ Prefix = 'SMS'; Name = 'AWS Sever Migration Service'; Url = 'https://aws.amazon.com/server-migration-service/'; Note = '' };
    'snowball'                     = [PSCustomObject]@{ Prefix = 'SNOW'; Name = 'AWS Snowball'; Url = 'https://aws.amazon.com/snowball/'; Note = '' };
    'sns'                          = [PSCustomObject]@{ Prefix = 'SNS'; Name = 'Amazon Simple Notification Service'; Url = 'https://aws.amazon.com/sns/'; Note = '' };
    'sqs'                          = [PSCustomObject]@{ Prefix = 'SQS'; Name = 'Amazon Simple Queue Service'; Url = 'https://aws.amazon.com/sqs/'; Note = '' };
    'ssm'                          = [PSCustomObject]@{ Prefix = 'SSM'; Name = 'AWS Systems Manager'; Url = 'https://aws.amazon.com/systems-manager/'; Note = '' };
    'stepfunctions'                = [PSCustomObject]@{ Prefix = 'SFN'; Name = 'AWS Step Functions'; Url = 'https://aws.amazon.com/step-functions/'; Note = '' };
    'storagegateway'               = [PSCustomObject]@{ Prefix = 'SG'; Name = 'AWS Storage Gateway'; Url = 'https://aws.amazon.com/storagegateway/'; Note = '' };
    'sts'                          = [PSCustomObject]@{ Prefix = 'STS'; Name = 'AWS Security Token Service'; Url = 'https://aws.amazon.com/iam/'; Note = '' };
    'support'                      = [PSCustomObject]@{ Prefix = 'ASA'; Name = 'AWS Support'; Url = 'https://aws.amazon.com/premiumsupport/'; Note = '' };
    'swf'                          = [PSCustomObject]@{ Prefix = 'SWF'; Name = 'Amazon Simple Workflow'; Url = 'https://aws.amazon.com/swf/'; Note = '' };
    'textract'                     = [PSCustomObject]@{ Prefix = 'TXT'; Name = 'Amazon Textract'; Url = 'https://aws.amazon.com/textract/'; Note = '' };
    'transcribe'                   = [PSCustomObject]@{ Prefix = 'TRS'; Name = 'Amazon Transcribe'; Url = 'https://aws.amazon.com/transcribe/'; Note = '' };
    'transfer'                     = [PSCustomObject]@{ Prefix = 'TFR'; Name = 'AWS Transfer for SFTP'; Url = 'https://aws.amazon.com/sftp/'; Note = '' };
    'translate'                    = [PSCustomObject]@{ Prefix = 'TRN'; Name = 'Amazon Translate'; Url = 'https://aws.amazon.com/translate/'; Note = '' };
    'waf'                          = [PSCustomObject]@{ Prefix = 'WAF'; Name = 'AWS WAF'; Url = 'https://aws.amazon.com/waf/'; Note = '' };
    'waf-regional'                 = [PSCustomObject]@{ Prefix = 'WAFR'; Name = 'AWS WAF Regional '; Url = 'https://aws.amazon.com/waf/'; Note = '' };
    'workdocs'                     = [PSCustomObject]@{ Prefix = 'WD'; Name = 'Amazon WorkDocs'; Url = 'https://aws.amazon.com/workdocs/'; Note = '' };
    'worklink'                     = [PSCustomObject]@{ Prefix = 'WL'; Name = 'Amazon WorkLink'; Url = 'https://aws.amazon.com/worklink/'; Note = '' };
    'workmail'                     = [PSCustomObject]@{ Prefix = 'WM'; Name = 'Amazon WorkMail'; Url = 'https://aws.amazon.com/workmail/'; Note = '' };
    'workspaces'                   = [PSCustomObject]@{ Prefix = 'WKS'; Name = 'Amazon WorkSpaces'; Url = 'https://aws.amazon.com/workspaces/'; Note = '' };
    'xray'                         = [PSCustomObject]@{ Prefix = 'XR'; Name = 'AWS X-Ray'; Url = 'https://aws.amazon.com/xray/'; Note = '' };
}

$g_CmdletReferenceLinks = @{
    'acm'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Certificate_Manager_cmdlets.html';
    'acm-pca'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Certificate_Manager_Private_Certificate_Authority_cmdlets.html';
    'alexaforbusiness'             = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Alexa_For_Business_cmdlets.html';
    'amplify'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Amplify_cmdlets.html';
    'apigateway'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_API_Gateway_cmdlets.html';
    'apigatewaymanagementapi'      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_API_Gateway_Management_API_cmdlets.html';
    'apigatewayv2'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_API_Gateway_V2_cmdlets.html';
    'application-autoscaling'      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Application_Auto_Scaling_cmdlets.html';
    'appmesh'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_App_Mesh_cmdlets.html';
    'appstream'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_AppStream_cmdlets.html';
    'appsync'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_AppSync_cmdlets.html';
    'athena'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Athena_cmdlets.html';
    'autoscaling'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Auto_Scaling_cmdlets.html';
    'autoscaling-plans'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Auto_Scaling_Plans_cmdlets.html';
    'backup'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Backup_cmdlets.html';
    'batch'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Batch_cmdlets.html';
    'budgets'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Budgets_cmdlets.html';
    'ce'                           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Cost_Explorer_cmdlets.html';
    'chime'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Chime_cmdlets.html';
    'cloud9'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Cloud9_cmdlets.html';
    'clouddirectory'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Cloud_Directory_cmdlets.html';
    'cloudformation'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CloudFormation_cmdlets.html';
    'cloudfront'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_CloudFront_cmdlets.html';
    'cloudhsm'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Cloud_HSM_cmdlets.html';
    'cloudhsmv2'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Cloud_HSM_V2_cmdlets.html';
    'cloudsearch'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_CloudSearch_cmdlets.html';
    'cloudsearchdomain'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_CloudSearchDomain_cmdlets.html';
    'cloudtrail'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CloudTrail_cmdlets.html';
    'cloudwatch'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_CloudWatch_cmdlets.html';
    'codebuild'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CodeBuild_cmdlets.html';
    'codecommit'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CodeCommit_cmdlets.html';
    'codepipeline'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CodePipeline_cmdlets.html';
    'codestar'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CodeStar_cmdlets.html';
    'cognito-identity'             = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Cognito_Identity_cmdlets.html';
    'cognito-idp'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Cognito_Identity_Provider_cmdlets.html';
    'cognito-sync'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Cognito_Sync_cmdlets.html';
    'comprehend'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Comprehend_cmdlets.html';
    'comprehendmedical'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Comprehend_Medical_cmdlets.html';
    'configservice'                = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Config_cmdlets.html';
    'configure'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Shell_Configuration_cmdlets.html';
    'connect'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Connect_Service_cmdlets.html';
    'cur'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Cost_and_Usage_Report_cmdlets.html';
    'datapipeline'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Data_Pipeline_cmdlets.html';
    'datasync'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_DataSync_cmdlets.html';
    'dax'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_DynamoDB_Accelerator_(DAX)_cmdlets.html';
    'deploy'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_CodeDeploy_cmdlets.html';
    'devicefarm'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Device_Farm_cmdlets.html';
    'directconnect'                = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Direct_Connect_cmdlets.html';
    'discovery'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Application_Discovery_Service_cmdlets.html';
    'dlm'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Data_Lifecycle_Manager_cmdlets.html';
    'dms'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Database_Migration_Service_cmdlets.html';
    'docdb'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_DocumentDB_cmdlets.html';
    'ds'                           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Directory_Service_cmdlets.html';
    'dynamodb'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_DynamoDB_cmdlets.html';
    'dynamodbstreams'              = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_DynamoDB_cmdlets.html';
    'ec2'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Elastic_Compute_Cloud_cmdlets.html';
    'ecr'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_EC2_Container_Registry_cmdlets.html';
    'ecs'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_EC2_Container_Service_cmdlets.html';
    'efs'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Elastic_File_System_cmdlets.html';
    'eks'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Elastic_Container_Service_for_Kubernetes_cmdlets.html';
    'elasticache'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_ElastiCache_cmdlets.html';
    'elasticbeanstalk'             = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elastic_Beanstalk_cmdlets.html';
    'elastictranscoder'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Elastic_Transcoder_cmdlets.html';
    'elb'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Elastic_Load_Balancing_cmdlets.html';
    'elbv2'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Elastic_Load_Balancing_V2_cmdlets.html';
    'emr'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Elastic_MapReduce_cmdlets.html';
    'es'                           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Elasticsearch_cmdlets.html';
    'events'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_CloudWatch_Events_cmdlets.html';
    'firehose'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Kinesis_Firehose_cmdlets.html';
    'fms'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Firewall_Management_Service_cmdlets.html';
    'fsx'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_FSx_cmdlets.html';
    'gamelift'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_GameLift_Service_cmdlets.html';
    'glacier'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Glacier_cmdlets.html';
    'globalaccelerator'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Global_Accelerator_cmdlets.html';
    'glue'                         = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Glue_cmdlets.html';
    'greengrass'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Greengrass_cmdlets.html';
    'groundstation'                = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Ground_Station_cmdlets.html';
    'guardduty'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_GuardDuty_cmdlets.html';
    'health'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Health_cmdlets.html';
    'history'                      = '';
    'iam'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Identity_and_Access_Management_cmdlets.html';
    'importexport'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Import_Export_cmdlets.html';
    'inspector'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Inspector_cmdlets.html';
    'iot'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_IoT_cmdlets.html';
    'iot-data'                     = '';
    'iot-jobs-data'                = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_IoT_Jobs_Data_Plane_cmdlets.html';
    'iot1click-devices'            = '';
    'iot1click-projects'           = '';
    'iotanalytics'                 = '';
    'iotevents-data'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_IoT_Events_Data_cmdlets.html';
    'iotevents'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_IoT_Events_cmdlets.html';
    'iotthingsgraph'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_IoT_Things_Graph_cmdlets.html';
    'kafka'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Managed_Streaming_for_Kafka_cmdlets.html';
    'kinesis'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Kinesis_cmdlets.html';
    'kinesis-video-archived-media' = '';
    'kinesis-video-media'          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Kinesis_Video_Streams_Media_cmdlets.html';
    'kinesisanalytics'             = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Kinesis_Analytics_cmdlets.html';
    'kinesisanalyticsv2'           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Kinesis_Analytics_(v2)_cmdlets.html';
    'kinesisvideo'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Kinesis_Video_Streams_cmdlets.html';
    'kms'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Key_Management_Service_cmdlets.html';
    'lambda'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Lambda_cmdlets.html';
    'lex-models'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Lex_Model_Building_Service_cmdlets.html';
    'lex-runtime'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Lex_cmdlets.html';
    'license-manager'              = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_License_Manager_cmdlets.html';
    'lightsail'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Lightsail_cmdlets.html';
    'logs'                         = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_CloudWatch_Logs_cmdlets.html';
    'machinelearning'              = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Machine_Learning_cmdlets.html';
    'macie'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Macie_cmdlets.html';
    'managedblockchain'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Managed_Blockchain_cmdlets.html';
    'marketplace-entitlement'      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Marketplace_Entitlement_Service_cmdlets.html';
    'marketplacecommerceanalytics' = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Marketplace_Commerce_Analytics_cmdlets.html';
    'mediaconnect'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaConnect_cmdlets.html';
    'mediaconvert'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaConvert_cmdlets.html';
    'medialive'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaLive_cmdlets.html';
    'mediapackage'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaPackage_cmdlets.html';
    'mediapackage-vod'             = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaPackage_VOD_cmdlets.html';
    'mediastore'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaStore_cmdlets.html';
    'mediastore-data'              = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaStore_Data_Plane_cmdlets.html';
    'mediatailor'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Elemental_MediaTailor_cmdlets.html';
    'meteringmarketplace'          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Marketplace_Metering_cmdlets.html';
    'mgh'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Migration_Hub_cmdlets.html';
    'mobile'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Mobile_cmdlets.html';
    'mq'                           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_MQ_cmdlets.html';
    'mturk'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_MTurk_Service_cmdlets.html';
    'neptune'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Neptune_cmdlets.html';
    'opsworks'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_OpsWorks_cmdlets.html';
    'opsworks-cm'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_OpsWorksCM_cmdlets.html';
    'organizations'                = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Organizations_cmdlets.html';
    'pi'                           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Performance_Insights_cmdlets.html';
    'pinpoint'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Pinpoint_cmdlets.html';
    'pinpoint-email'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Pinpoint_Email_cmdlets.html';
    'pinpoint-sms-voice'           = '';
    'polly'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Polly_cmdlets.html';
    'pricing'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Price_List_Service_cmdlets.html';
    'quicksight'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_QuickSight_cmdlets.html';
    'ram'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Resource_Access_Manager_cmdlets.html';
    'rds'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Relational_Database_Service_cmdlets.html';
    'rds-data'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_RDS_DataService_cmdlets.html';
    'redshift'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Redshift_cmdlets.html';
    'rekognition'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Rekognition_cmdlets.html';
    'resource-groups'              = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Resource_Groups_cmdlets.html';
    'resourcegroupstaggingapi'     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Resource_Groups_Tagging_API_cmdlets.html';
    'robomaker'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_RoboMaker_cmdlets.html';
    'route53'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Route_53_cmdlets.html';
    'route53domains'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Route_53_Domains_cmdlets.html';
    'route53resolver'              = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Route_53_Resolver_cmdlets.html';
    's3'                           = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Simple_Storage_Service_cmdlets.html';
    's3api'                        = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Simple_Storage_Service_cmdlets.html';
    's3control'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_S3_Control_cmdlets.html';
    'sagemaker'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_SageMaker_Service_cmdlets.html';
    'sagemaker-runtime'            = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_SageMaker_Runtime_cmdlets.html';
    'sdb'                          = '';
    'secretsmanager'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Secrets_Manager_cmdlets.html';
    'securityhub'                  = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Security_Hub_cmdlets.html';
    'serverlessrepo'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Serverless_Application_Repository_cmdlets.html';
    'servicecatalog'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Service_Catalog_cmdlets.html';
    'servicediscovery'             = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Route_53_Auto_Naming_cmdlets.html';
    'ses'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Simple_Email_Service_cmdlets.html';
    'shield'                       = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Shield_cmdlets.html';
    'signer'                       = '';
    'sms'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Server_Migration_Service_cmdlets.html';
    'snowball'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Import_Export_Snowball_cmdlets.html';
    'sns'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Simple_Notification_Service_cmdlets.html';
    'sqs'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Simple_Queue_Service_cmdlets.html';
    'ssm'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Systems_Manager_cmdlets.html';
    'stepfunctions'                = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Step_Functions_cmdlets.html';
    'storagegateway'               = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Storage_Gateway_cmdlets.html';
    'sts'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Security_Token_Service_cmdlets.html';
    'support'                      = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Support_API_cmdlets.html';
    'swf'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Simple_Workflow_Service_cmdlets.html';
    'textract'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Textract_cmdlets.html';
    'transcribe'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Transcribe_Service_cmdlets.html';
    'transfer'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_Transfer_for_SFTP_cmdlets.html';
    'translate'                    = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_Translate_cmdlets.html';
    'waf'                          = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_WAF_cmdlets.html';
    'waf-regional'                 = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_WAF_Regional_cmdlets.html';
    'workdocs'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_WorkDocs_cmdlets.html';
    'worklink'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_WorkLink_cmdlets.html';
    'workmail'                     = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_WorkMail_cmdlets.html';
    'workspaces'                   = 'https://docs.aws.amazon.com/powershell/latest/reference/items/Amazon_WorkSpaces_cmdlets.html';
    'xray'                         = 'https://docs.aws.amazon.com/powershell/latest/reference/items/AWS_X-Ray_cmdlets.html';
}